title: "Federico Gatta"
description: "PhD Candidate in Computational Methods and Mathematical Models for Sciences and Finance, Scuola Normale Superiore"
baseurl: ""
url: "https://federico-gatta.github.io"

author:
  name: "Federico Gatta"
  email: "fede.gatta96@gmail.com"
  linkedin: "https://linkedin.com/in/federico-gatta-19na96"

# REMOVE the line below if it exists:
# theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
