title: "Federico Gatta"
description: "PhD Candidate in Computational Methods and Mathematical Models for Sciences and Finance, Scuola Normale Superiore"
baseurl: ""
url: "https://federico-gatta.github.io"
theme: null
markdown: kramdown

# Navigation
nav_pages:
  - title: "Home"
    url: "/"
  - title: "Papers"
    url: "/papers/"
  - title: "Talks"
    url: "/talks"
  - title: "CV"
    url: "/cv"

# Footer info
author:
  name: "Federico Gatta"
  email: "fede.gatta96@gmail.com"
  linkedin: "https://linkedin.com/in/federico-gatta-19na96"

